[profile.default]
test = "test"
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.7.6"

[rpc_endpoints]
arbitrum = "${ARBITRUM_MAINNET_API}"

[etherscan]
arbitrum = { key = "${ARBSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
